apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: omar-test-secrets
  namespace: omar-test
spec:
  provider: aws
  parameters:
    objects: |
      - objectName: "OMAR_SECRET_BAR"
        objectType: "secretsmanager"
  secretObjects:
    - secretName: omar-test-secrets
      type: Opaque
      data:
        - objectName: OMAR_SECRET_BAR
          key: OMAR_SECRET_BAR
